// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormButton: typeof import('./components/FormButton.vue')['default']
    FormInput: typeof import('./components/FormInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheForm: typeof import('./components/TheForm.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
